### ISSUE TITLE
Disable initial animation

### ISSUE THREAD

**Issue by Wykks** [swiety85/angular2gridster#104]
Is there a way to disable the small initial animation ? The animation is weird and laggy when using lots of items and heavy components inside.

**Comment by swiety85** [comment]
There is no configuration for angular2gridster. I will prevent this animation on initial load in the project by default in one of the following releases.
As a temporary solution you can prevent it as follows:
_In the component that renders Gridster:_
```js
    preventAnimation = false;
    ngAfterViewInit() {
        setTimeout(() => this.preventAnimation = false, 1000);
    }
```
_In template:_
```html
<gridster ...>
        <gridster-item ... [ngClass]="{'prevent-animation': preventAnimation}"> ... </gridster-item>
</gridster>
```
_In style.css:_
```css
.prevent-animation {
    -webkit-transition: none !important;
    transition: none !important;
}
```
