### ISSUE TITLE
gridster-item margin

### ISSUE THREAD

**Issue by duke83** [swiety85/angular2gridster#153]
I'm really digging angular2gridster! My issue is that I am trying to increase the space between gridster items. I tried the following:
    gridster-item{margin:30px;}
but it did not add space between gridster items. Any ideas?
Thanks

**Comment by swiety85** [comment]
Hi,
for applying margin on gridster items is responsible `.gridster-item-inner` element that is direct child of each girdster-item. In demo margin is defined by following css:
```css
.gridster-item-inner {
    position: absolute;
    top: 5px;
    bottom: 5px;
    left: 5px;
    right: 5px;
    ...
}
```
Or you can use margin as follows:
```css
.gridster-item-inner {
    position: relative;
    width: calc(100% - 10px);
    height: calc(100% - 10px);
    margin: 5px;
    ...
}
```
Hope I helped you.
