### ISSUE TITLE
How to change cursor during drag?

### ISSUE THREAD

**Issue by IAMtheIAM** [swiety85/angular2gridster#161]
Hi, great framework. I'm trying to change the cursor during drag. Using CSS only doesnt seem to work.

gridsterItemPrototype

```scss

   .panel-heading {
      cursor: -moz-grab;
      cursor: -webkit-grab;
      cursor: grab;
   }

   .is-dragging {
      .panel-heading {
         cursor: move;
      }
   }
```

It stays as `grab` when hovering and during drag, and as soon as I let go of the mouse after drag, it flashes to the `move` and then back to `drag`.

So I figured I can try with javascript.

There is `GridsterItemComponent` and `gridsterItemPrototypeDirective`. Which one is better to use? What is the difference? I can't find the difference based on the docs, seems like they are two ways to do the same thing? Both have `start` and `end` drag events. Thanks for any help.
